# Introduction to NumPy

• NumPy is a Python package and it stands for numerical python 
• Fundamental package for numerical computations in Python

•Supports N-dimensional array objects that can be used for processing multidimensional data

•Supports different data-types

# Array

• An array is a data structure that stores values of same data type

•Lists can contain values corresponding to different data types,

•Arrays in python can only contain values corresponding to same data type

# NumPy Array

•A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers

•The number of dimensions is the rank of the array

• The shape of an array is a tuple of integers giving the size of the array along each dimension

# Creation of Array

In [1]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


## To create numpy array we need to import a numpy package:


In [2]:
import numpy as np

In [3]:
array = np.array(my_list, dtype = int)
print(array)

[1 2 3 4 5 6]


In [4]:
print(type(array))
print(len(array))
print(array.ndim)  # number of dimenssion of array
print(array.shape) # size along each dimenssion

<class 'numpy.ndarray'>
6
1
(6,)


In [9]:
# Changing shape of an array  will reshape it with 3 rows and 2 coloumns
array2 = array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [11]:
array3 = array.reshape(3,-1)  # 3 rows and 2 coloumns automatically
print(array3)

print(array3.ndim)           # 2 dimension because rows and coloumn

[[1 2]
 [3 4]
 [5 6]]
2


In [20]:
## initiallazing numpy array from nested python lists

my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,6,5]
my_list4 = [9,7,6,8,9]

mul_arr = np.array([my_list2, my_list3, my_list4 ]) 
# here we are passing 3 lists under onelist

print(mul_arr) 
# multidimentional array

print(mul_arr.shape)


[[1 2 3 4 5]
 [2 3 4 6 5]
 [9 7 6 8 9]]
(3, 5)


In [23]:
mul_arr.reshape(1,15)    # single row and 15 coloumns

array([[1, 2, 3, 4, 5, 2, 3, 4, 6, 5, 9, 7, 6, 8, 9]])

# NumPy - Attributes

In [5]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [6]:
# ReShaping Array
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
r = range(24)

In [9]:
print(r)

range(0, 24)


In [12]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print("Dinenssion of array is",a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Dinenssion of array is 1


In [16]:
#Reshaping the array "a"
b = a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


## NumPy Arithematic Operations on arrays

In [20]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(x)
print(y)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


## numpy.add() - performs elementwise addition between 2 arrays

syntax : numpy.add(array_1,array_2)

In [25]:
print(x + y)

print("-"*80)
# OR

print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
--------------------------------------------------------------------------------
[[ 6.  8.]
 [10. 12.]]


## numpy.subtract() - performs elementwise subtraction between 2 arrays

syntax : numpy.subtract(array_1,array_2)

In [22]:
print(x - y)

print("-"*80)
# OR

print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


## numpy.subtract() - performs elementwise subtraction between 2 arrays

syntax : numpy.multiply(array_1,array_2)

In [23]:
print(x * y)

print("-"*80)
# OR

print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [27]:
# for dot product 
print(x.dot(y))

print("-"*80)
# OR

print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [29]:
# For division

print(x / y)

print("-"*80)
# OR

print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
--------------------------------------------------------------------------------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## numpy.sum() - returns sum of all array elements or sum of all array elements over a given axis

syntax : numpy.sum(array,axis)

In [37]:
print(x)

[[1. 2.]
 [3. 4.]]


In [38]:
print(np.sum(x))     # compute overall sum (axis=none)

10.0


In [39]:
print(np.sum(x, axis =0))  # compute sum of each column

[4. 6.]


In [40]:
print(np.sum(x, axis =1))  # compute sum of each row

[3. 7.]
